return {
	"AstroNvim/astrocommunity",
	event = "VeryLazy",
	-- { import = "astrocommunity.debugging.nvim-bqf" },
	-- { import = "astrocommunity.code-runner.overseer-nvim" },
	{ import = "astrocommunity.code-runner.sniprun" },
	{ import = "astrocommunity.bars-and-lines.scope-nvim" },
	-- { import = "astrocommunity.colorscheme.gruvbox" },
	-- { import = "astrocommunity.colorscheme.kanagawa" },
	-- { import = "astrocommunity.colorscheme.tokyonight" },
	-- { import = "astrocommunity.colorscheme.oxocarbon" },
	-- { import = "astrocommunity.colorscheme.nightfox" },
	-- { import = "astrocommunity.colorscheme.rose-pine" },
	-- { import = "astrocommunity.editing-support.auto-save-nvim" },
	{ import = "astrocommunity.editing-support.mini-splitjoin" },
	{ import = "astrocommunity.editing-support.dial-nvim" },
	-- { import = "astrocommunity.editing-support.refactoring-nvim" },
	{ import = "astrocommunity.editing-support.todo-comments-nvim" },
	{ import = "astrocommunity.editing-support.nvim-regexplainer" },
	{ import = "astrocommunity.editing-support.neogen" },
	{ import = "astrocommunity.editing-support.nvim-ts-rainbow" },
	{ import = "astrocommunity.editing-support.zen-mode-nvim" },
	{ import = "astrocommunity.file-explorer.oil-nvim" },
	{ import = "astrocommunity.markdown-and-latex.glow-nvim" },
	{ import = "astrocommunity.markdown-and-latex.markdown-preview-nvim" },
	-- { import = "astrocommunity.media.drop-nvim" },
	-- { "drop.nvim",                                                       opts = { theme = "stars" } },
	{ import = "astrocommunity.media.pets-nvim" },
	{ import = "astrocommunity.media.presence-nvim" },
	{ import = "astrocommunity.media.vim-wakatime" },
	-- { import = "astrocommunity.note-taking.neorg" },
	{ import = "astrocommunity.pack.go" },
	{ import = "astrocommunity.pack.yaml" },
	{ import = "astrocommunity.pack.typescript" },
	{ import = "astrocommunity.pack.json" },
	{ import = "astrocommunity.pack.markdown" },
	{ import = "astrocommunity.pack.lua" },
	{ import = "astrocommunity.project.neoconf-nvim" },
	{ import = "astrocommunity.syntax.vim-easy-align" },
	{ import = "astrocommunity.syntax.hlargs-nvim" },
	{ import = "astrocommunity.motion.mini-move" },
	{ import = "astrocommunity.motion.nvim-surround" },
	{ import = "astrocommunity.motion.mini-bracketed" },
	{ import = "astrocommunity.motion.mini-ai" },
	{ import = "astrocommunity.motion.leap-nvim" },
	{ import = "astrocommunity.utility.noice-nvim" },
	{ import = "astrocommunity.project.project-nvim" },
	{
		"project.nvim",
		opts = {
			show_hidden = true,
		},
	},
	{ import = "astrocommunity.diagnostics.lsp_lines-nvim" },
	{ import = "astrocommunity.diagnostics.trouble-nvim" },
	{ import = "astrocommunity.utility.neodim" },
	{ import = "astrocommunity.indent.mini-indentscope" },
	{ import = "astrocommunity.bars-and-lines.statuscol-nvim" },
	{ import = "astrocommunity.scrolling.mini-animate" },
	{ import = "astrocommunity.scrolling.nvim-scrollbar" },
	{ import = "astrocommunity.syntax.hlargs-nvim" },
	{ import = "astrocommunity.syntax.vim-easy-align" },
	{ import = "astrocommunity.terminal-integration.flatten-nvim" },
	{ import = "astrocommunity.color.headlines-nvim" },
	{ import = "astrocommunity.color.tint-nvim" },
	{ import = "astrocommunity.color.twilight-nvim" },
	{ import = "astrocommunity.test.nvim-coverage" },
}
